[package]
name = "api"
version = "0.0.1"
edition = "2021"

[dependencies]
spec = { path = "../spec" }
corelib = { path = "../corelib" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
